### ISSUE TITLE
Improve findability in github search

### ISSUE THREAD

**Issue by agricolab** [labstreaminglayer/liblsl-Python#14]
I just found out that a search in github for  ```pylsl``` does not show this repo. This is likely because neither title nor description contain this term. Github looks also into the description when searching. Adding ```pylsl```and possibly also ```labstreaminglayer``` and ```LSL``` to the description would therefore probably solve this issue. Another option are adding topics, they are searchable with hashtags.

**Comment by tstenner** [comment]
I added pylsl to the description and labstreaminglayer and lsl to the topics. We're now at #2 when searching for pylsl.
