### ISSUE TITLE
Bug: Receive and Plot Example stuck at "looking for an EEG stream..."

### ISSUE THREAD

**Issue by jzingh98** [labstreaminglayer/liblsl-Python#17]
Bug seems to be arising in the call to resolve_stream in the statement 

resolve_stream('type', 'Markers')

**Comment by agricolab** [comment]
Did you also stream markers, e.g by running SendStringMarkers.py in a separate process? https://github.com/labstreaminglayer/liblsl-Python/blob/master/pylsl/examples/SendStringMarkers.py

**Comment by jzingh98** [comment]
I did not! Apologies and thanks for clarifying. It should work now
