### ISSUE TITLE
No support for variable-length binary data

### ISSUE THREAD

**Issue by papr** [labstreaminglayer/liblsl-Python#7]
The XDF format specification explicitly states support for
> [non-numeric (i.e., string or binary) values, [with] a variable-length encoding](https://github.com/sccn/xdf/wiki/Specifications#structure-of-value)

To my knowledge, the only supported variable-length type in `pylsl` is `pylsl.cf_string`.

The issue is that the [`pylsl.StreamOutlet.push_sample()` implementation](https://github.com/labstreaminglayer/liblsl-Python/blob/f9234acf3f1821e254f828ed1798a7623a7c18b7/pylsl/pylsl.py#L449) only accepts unicode strings. It does not support objects of type `bytes`, etc.

Is there a reason why byte-like objects are not supported?

Suggested solution: Wrap the `.encode("utf-8")` in a try-except block that catches the attribute error in case the user passed bytes-like objects, see https://stackoverflow.com/a/34870210.

I would like to start working on a PR as soon as one of the developers (maybe @cboulay) confirms the issue and signs off on the suggested solution.

Motivation: Support for variable-length binary data is crucial for the upcoming [Pupil Labs LSL Relay plugin](https://github.com/pupil-labs/pupil/issues/1281#issuecomment-457985626) changes.

**Comment by mgrivich** [comment]
Please read and move the discussion to this issue:  [Add support for variable length typed data](https://github.com/sccn/labstreaminglayer/issues/9)
