### ISSUE TITLE
Missing cf_int64 support needs better error message

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/liblsl-Python#9]
Currently there are no lib.lsl_push_ or lib.lsl_pull_ methods mapped for cf_int64.
However, when one attempts to use this format, the error returned is `'list' object is not callable`, because instead of a proper method, the map returns `[]`.

I think there needs to be an error raised when a stream is opened with this channel format.

**Comment by tstenner** [comment]
They are there, just not on 32bit platforms and Windows ([see here](https://stackoverflow.com/a/384672/73299)). I've created a PR to address the issue (#20).
